### ISSUE TITLE
suggestions for README

### ISSUE THREAD

**Issue by SCEDC** [SeisSCOPED/seis_cloud#1]
Include the step for git clone

_git clone https://github.com/SeisSCOPED/seis_cloud.git_
_cd seis_cloud_
conda create -y -n seiscloud python=3.8 pip
conda activate seiscloud
pip install -r requirements.txt

The section "Tutorial documentation and links" I would put this either at the beginning or the end and say something like "Running and installing seis_cloud in AWS"  It looks like these steps overlap with the instructions on that link.

**Comment by niyiyu** [comment]
Sorry for this late reply. I have addressed this in the README. Thanks for this suggestion!

Cheers,
Yiyu
